#!/bin/sh

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:$PATH

mkdir -p /proc /sys /run /tmp /var

/bin/mount -a

mkdir -p /var/log /var/lock /var/run /var/tmp /var/lib

[ -x /sbin/mdev ] && /sbin/mdev -s

# /bin/hostname am62x

echo "=== System basic initialization completed ==="

for i in /etc/init.d/S??* ; do
    [ ! -f "$i" ] && continue
    case "$i" in
        *.sh) (trap - INT QUIT TSTP; set start; . $i) ;;
        *) $i start ;;
    esac
done
